<h1>This is where calendar shown!</h1>
<?php
/** @var \Uet\Calendar\Block\Occasions $block */
$categories = $block->getCategories();
?>
<h1>Occasions</h1>
<div class="messages" id="alert-block" style="display: none; padding: 10px; margin-top: 10px; border-radius: 5px; color:white; font-weight: 600;">
</div>
<div class="grid-container">
    <div class="grid-column flex-column-gap" id="custom-section-container" 
        data-destroy-url="<?= $block->getUrl('calendar/action/destroy') ?>"
        data-form-key="<?= $block->getFormKey() ?>"
    >
        <div id="loading-icon">Loading...</div>
    </div>

    <div class="grid-column">
        <div id="mode-display">
            <div style="display:flex; justify-content:space-between;">
                <div>You are: <span id="mode-status">Adding an occasion</span></div>
                <button id="add-mode" disabled="true" type="button" onclick="changeMode()">Add mode</button>
            </div>
        </div>
        <form class="form-style" id="add" action="<?= $block->getUrl('calendar/action/save') ?>" method="post">
            <input type="hidden" id="form_key" name="form_key" value="<?= $block->getFormKey() ?>">
            <input id="occasion-id" type="hidden" name="id">
            <input id="customer-id" type="hidden" name="customer_id">
            <div>
                <label for="name">Occasion:</label>
                <select name="occasion" id="occasion" required>
                    <?php foreach ($categories as $category): ?>
                        <option value="<?= $category['name'] ?>"><?= $category['name'] ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div>
                <label for="date">Date:</label>
                <input type="date" name="date" id="date" required>
            </div>
            <div>
                <label for="note">Note:</label>
                <input type="text" name="note" id="note" required>
            </div>
            <div>
                <button type="submit">Save Occasion</button>
            </div>
        </form>
    </div>
</div>

<style>
    .grid-container {
        display: grid;
        grid-template-columns: repeat(2, 1fr); /* Adjust the number of columns as needed */
        gap: 10px; /* Adjust the gap between columns as needed */
    }

    .grid-column {
        padding: 10px;
        box-sizing: border-box;
    }

    .form-style{
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    .flex-column-gap{
        display: flex;
        flex-direction: column;
        gap: 5px;
    }

    .flex-row-end{
        display: flex;
        flex-direction: row;
        gap: 10px;
        justify-content: end;
    }

    .occasion-item{
        border: 2px solid lightgray;
        padding: 10px;
        border-radius: 10px;
    }

    .occasion-item-choose{
        border: 2px solid black;
        background-color: lightgray;
    }

    .highlight{
        border: 2px solid black;
        background-color: lightgray;
    }

</style>

<script type="text/javascript">

    require(['jquery','Magento_Customer/js/customer-data', 'domReady!'], function ($, customerData) {
        var customSection = customerData.get('custom_section');
        //ustomerData.reload(['custom_section'], true);  
        customSection.subscribe(function (data) {
            //console.log(data);
            var container = document.getElementById('custom-section-container');
            var destroyUrl = container.getAttribute('data-destroy-url');
            var formKey = document.getElementById('form_key').value;
            document.getElementById('customer-id').value = data.customer_id;
            if (container) {
                container.innerHTML = ''; // Clear existing content
                if(data.occasions.length == 0){
                    container.innerHTML = '<div>No occasions found.</div>';
                }
                data.occasions.forEach(function (occasion) {
                    var li = document.createElement('div');
                    li.classList.add('grid-container');
                    li.classList.add('occasion-item');
                    li.id = 'occasion-' + occasion.id;
                    li.innerHTML = 
                        '<div>' 
                            + '<span style="text-transform: uppercase; font-weight:bold;">' + occasion.occasion + '</span>' + 
                            '  ' + occasion.date + '<br>' +
                            (occasion.note ? occasion.note : 'No additional notes available.') +
                        '</div>' +
                        '<div class="flex-row-end">' +
                            '<form id="del" action="' + destroyUrl + '" method="post" style="display:inline;">' +
                                '<input type="hidden" name="form_key" value="' + formKey + '">' +
                                '<input type="hidden" name="id" value="' + occasion.id + '">' +
                                '<button style="height: 100%;" type="submit" onclick="return confirm(\'Are you sure you want to delete this occasion?\');">Delete</button>' +
                            '</form>' +
                            '<button class="update-button" type="button" onclick="populateForm(\'' + occasion.id + '\', \'' + occasion.occasion + '\', \'' + occasion.date + '\', \'' + occasion.note + '\')">Update</button>' +
                        '</div>';
                    container.appendChild(li);
                });
            }
        });

        $(document).on('submit', '#del', function (event) {
            event.preventDefault(); // Prevent the default form submission
            var form = $(this);

            var occasionId = $('#occasion-id').val();

            if (occasionId) {
                $('#occasion-id').val('');
                $('#add').find('input:not([type="hidden"])').val('');
                $('#add').find('select').prop('selectedIndex', 0);
            }

            $.ajax({
                type: 'POST',
                url: form.attr('action'),
                data: form.serialize(),
                success: function (response) {
                    console.log(response);
                    showAlert(response.message, 'success');
                    removeMessage();
                },
                error: function () {
                    showAlert(response.message, 'error');
                    console.log('Error del');
                }
            });
        });

        $(document).on('submit', '#add', function (event) {
            event.preventDefault(); // Prevent the default form submission
            var form = $(this);

            var occasionId = $('#occasion-id').val();

            $.ajax({
                type: 'POST',
                url: form.attr('action'),
                data: form.serialize(),
                success: function (response) {
                    changeMode();
                    showAlert(response.message, 'success');
                    removeMessage();
                },
                error: function () {
                    showAlert(response.message, 'error');
                    console.log('Error add');
                }
            });
        });

        function removeMessage() {
            setTimeout(function () {
                $('.messages').fadeOut('slow', function () {
                    $(this).css('display', 'none');
                });
            }, 3000);
        } // 3 seconds

        function showAlert(message, type) {
            var alertBlock = document.getElementById('alert-block');
            alertBlock.style.display = 'block';
            alertBlock.style.backgroundColor = type === 'error' ? 'red' : 'green';
            alertBlock.innerHTML = message;
            removeMessage();
        }

    });

    function populateForm(id, occasion, date, note) {
        var selectElement = document.getElementById('occasion');
        //console.log(id + ' - ' + occasion + ' - ' + date + ' - ' + note);
        document.getElementById('occasion-id').value = id;
        for (var i = 0; i < selectElement.options.length; i++) {
            if (selectElement.options[i].value === occasion) {
            // Set the matched option as selected
            selectElement.selectedIndex = i;
            break;
            }
        }
        document.getElementById('date').value = date;
        document.getElementById('note').value = note;

        // Highlight the current div
        var occasionItems = document.querySelectorAll('.occasion-item');
        occasionItems.forEach(function(item) {
            item.classList.remove('highlight'); // Remove highlight from all items
        });
        document.getElementById('occasion-' + id).classList.add('highlight'); // Add highlight to the current item

        // Enable the "Add mode" button
        document.getElementById('add-mode').disabled = false;
        document.getElementById('mode-status').innerHTML = "Updating an occasion";

    }

    function changeMode(){
        
        var occasionItems = document.querySelectorAll('.occasion-item');
        occasionItems.forEach(function(item) {
            item.classList.remove('highlight'); // Remove highlight from all items
        });
        document.getElementById('mode-status').innerHTML = "Adding an occasion";
        document.getElementById('add-mode').disabled = true;
        document.getElementById('occasion-id').value = '';
        document.getElementById('date').value = '';
        document.getElementById('note').value = '';

    }


</script>
